"""Added new column service_name

Revision ID: 32fe372cfa2f
Revises: 2654bac9d074
Create Date: 2026-06-11 02:34:00.449484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fe372cfa2f'
down_revision: Union[str, Sequence[str], None] = '2654bac9d074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('service_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'service_type')
    # ### end Alembic commands ###
