"""add_agent_engine_tables

Revision ID: 6fec7380f453
Revises: 9b315d9b3aaa
Create Date: 2026-06-26 18:22:05.660580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fec7380f453'
down_revision: Union[str, Sequence[str], None] = '9b315d9b3aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omnichannel_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=True),
    sa.Column('channel_source', sa.String(length=50), nullable=False),
    sa.Column('conversation_state', sa.String(length=30), nullable=False),
    sa.Column('active_action', sa.String(length=50), nullable=True),
    sa.Column('active_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_omnichannel_sessions_bot_id'), 'omnichannel_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_omnichannel_sessions_session_id'), 'omnichannel_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_omnichannel_sessions_tenant_id'), 'omnichannel_sessions', ['tenant_id'], unique=False)
    op.create_table('lead_captures',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('metadata_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['omnichannel_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_captures_bot_id'), 'lead_captures', ['bot_id'], unique=False)
    op.create_index(op.f('ix_lead_captures_id'), 'lead_captures', ['id'], unique=False)
    op.create_index(op.f('ix_lead_captures_tenant_id'), 'lead_captures', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_captures_tenant_id'), table_name='lead_captures')
    op.drop_index(op.f('ix_lead_captures_id'), table_name='lead_captures')
    op.drop_index(op.f('ix_lead_captures_bot_id'), table_name='lead_captures')
    op.drop_table('lead_captures')
    op.drop_index(op.f('ix_omnichannel_sessions_tenant_id'), table_name='omnichannel_sessions')
    op.drop_index(op.f('ix_omnichannel_sessions_session_id'), table_name='omnichannel_sessions')
    op.drop_index(op.f('ix_omnichannel_sessions_bot_id'), table_name='omnichannel_sessions')
    op.drop_table('omnichannel_sessions')
    # ### end Alembic commands ###
