"""Test_from_admin

Revision ID: a7cec46e4105
Revises: e221a0ab5c74
Create Date: 2026-06-28 17:59:38.445144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7cec46e4105'
down_revision: Union[str, Sequence[str], None] = 'e221a0ab5c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('lead_captures', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_captures', 'updated_at')
    op.drop_column('bookings', 'updated_at')
    # ### end Alembic commands ###
