"""add_discount_amount_to_bookings

Revision ID: cfdd81a424ef
Revises: fdd02269254f
Create Date: 2026-06-11 23:15:32.213506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdd81a424ef'
down_revision: Union[str, Sequence[str], None] = 'fdd02269254f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
