"""init_tenant_tables

Revision ID: e221a0ab5c74
Revises: 
Create Date: 2026-06-28 17:44:00.848080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e221a0ab5c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('omnichannel_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=True),
    sa.Column('channel_source', sa.String(length=50), nullable=False),
    sa.Column('conversation_state', sa.String(length=30), nullable=False),
    sa.Column('active_action', sa.String(length=50), nullable=True),
    sa.Column('active_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_omnichannel_sessions_bot_id'), 'omnichannel_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_omnichannel_sessions_session_id'), 'omnichannel_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_omnichannel_sessions_tenant_id'), 'omnichannel_sessions', ['tenant_id'], unique=False)
    op.create_table('lead_captures',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('metadata_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['omnichannel_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_captures_bot_id'), 'lead_captures', ['bot_id'], unique=False)
    op.create_index(op.f('ix_lead_captures_id'), 'lead_captures', ['id'], unique=False)
    op.create_index(op.f('ix_lead_captures_tenant_id'), 'lead_captures', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_captures_tenant_id'), table_name='lead_captures')
    op.drop_index(op.f('ix_lead_captures_id'), table_name='lead_captures')
    op.drop_index(op.f('ix_lead_captures_bot_id'), table_name='lead_captures')
    op.drop_table('lead_captures')
    op.drop_index(op.f('ix_omnichannel_sessions_tenant_id'), table_name='omnichannel_sessions')
    op.drop_index(op.f('ix_omnichannel_sessions_session_id'), table_name='omnichannel_sessions')
    op.drop_index(op.f('ix_omnichannel_sessions_bot_id'), table_name='omnichannel_sessions')
    op.drop_table('omnichannel_sessions')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
