"""add billing and widget fields to tenant

Revision ID: 20cf5f44d9af
Revises: 42bf323d8cdd
Create Date: 2026-06-17 20:23:56.375800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20cf5f44d9af'
down_revision: Union[str, Sequence[str], None] = '42bf323d8cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('monthly_token_usage', sa.Integer(), nullable=False), schema='assistly_auth')
    op.add_column('tenants', sa.Column('widget_api_key_hash', sa.String(length=255), nullable=True), schema='assistly_auth')
    op.drop_column('tenants', 'created_at', schema='assistly_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False), schema='assistly_auth')
    op.drop_column('tenants', 'widget_api_key_hash', schema='assistly_auth')
    op.drop_column('tenants', 'monthly_token_usage', schema='assistly_auth')
    # ### end Alembic commands ###
