"""add name to users

Revision ID: 2d2aa0d131db
Revises: b413084f87bd
Create Date: 2026-06-15 10:14:40.285572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2aa0d131db'
down_revision: Union[str, Sequence[str], None] = 'b413084f87bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True), schema='assistly_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name', schema='assistly_auth')
    # ### end Alembic commands ###
