"""added tenant member junction and fixed user roles

Revision ID: 42bf323d8cdd
Revises: 92c7e7de2bf4
Create Date: 2026-06-17 13:18:48.090892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42bf323d8cdd'
down_revision: Union[str, Sequence[str], None] = '92c7e7de2bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_cycle_anchor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['assistly_auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['assistly_auth.users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    schema='assistly_auth'
    )
    op.create_table('tenant_members',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['assistly_auth.tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['assistly_auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uix_user_tenant_membership'),
    schema='assistly_auth'
    )
    op.drop_table('tenant', schema='assistly_auth')
    op.add_column('addresses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True), schema='assistly_auth')
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), nullable=False), schema='assistly_auth')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False), schema='assistly_auth')
    op.add_column('users', sa.Column('last_active_tenant_slug', sa.String(length=255), nullable=True), schema='assistly_auth')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False), schema='assistly_auth')
    op.drop_column('users', 'role', schema='assistly_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='assistly_auth')
    op.drop_column('users', 'updated_at', schema='assistly_auth')
    op.drop_column('users', 'last_active_tenant_slug', schema='assistly_auth')
    op.drop_column('users', 'is_verified', schema='assistly_auth')
    op.drop_column('users', 'is_system_admin', schema='assistly_auth')
    op.drop_column('addresses', 'deleted_at', schema='assistly_auth')
    op.create_table('tenant',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('plan_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('subscription_cycle_anchor', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('trial_end_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['assistly_auth.users.id'], name=op.f('tenant_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['assistly_auth.users.id'], name=op.f('tenant_owner_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_pkey')),
    sa.UniqueConstraint('slug', name=op.f('tenant_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('stripe_customer_id', name=op.f('tenant_stripe_customer_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('stripe_subscription_id', name=op.f('tenant_stripe_subscription_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='assistly_auth'
    )
    op.drop_table('tenant_members', schema='assistly_auth')
    op.drop_table('tenants', schema='assistly_auth')
    # ### end Alembic commands ###
