"""add billing and widget fields to tenant

Revision ID: 89ee645fbd8d
Revises: 20cf5f44d9af
Create Date: 2026-06-17 20:32:33.187699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ee645fbd8d'
down_revision: Union[str, Sequence[str], None] = '20cf5f44d9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('website_url', sa.String(length=255), nullable=True), schema='assistly_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'website_url', schema='assistly_auth')
    # ### end Alembic commands ###
