"""add profile fields to users

Revision ID: 92c7e7de2bf4
Revises: 2d2aa0d131db
Create Date: 2026-06-15 14:41:12.708077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c7e7de2bf4'
down_revision: Union[str, Sequence[str], None] = '2d2aa0d131db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True), schema='assistly_auth')
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True), schema='assistly_auth')
    op.add_column('users', sa.Column('timezone', sa.String(length=100), nullable=True), schema='assistly_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone', schema='assistly_auth')
    op.drop_column('users', 'bio', schema='assistly_auth')
    op.drop_column('users', 'phone', schema='assistly_auth')
    # ### end Alembic commands ###
