"""added new fields to tenant

Revision ID: 9e6c922bc035
Revises: 89ee645fbd8d
Create Date: 2026-06-29 13:04:52.647639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6c922bc035'
down_revision: Union[str, Sequence[str], None] = '89ee645fbd8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False), schema='assistly_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'created_at', schema='assistly_auth')
    # ### end Alembic commands ###
